In [3]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Karan\Downloads\netflix_titles.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [ ]:
import numpy as np
idk = df['country'].str.split(',').explode().replace('',np.nan).dropna().str.strip().sort_values().unique()
idk1 = pd.Series(idk)
idk1.count()
idk1

#countries were repeating because i didnt strip the ones that were split.... bye

0       Afghanistan
1           Albania
2         Argentina
3           Armenia
4         Australia
           ...
105    Vatican City
106       Venezuela
107         Vietnam
108    West Germany
109        Zimbabwe
Length: 110, dtype: str

In [ ]:
df[df['country'].isin(['United States'])].head()
#so the movies/tv shows with multiple countries arent showing up... hmm

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
8,80117902,TV Show,Fire Chasers,NaN,NaN,United States,"September 8, 2017",2017,TV-MA,1 Season,"Docuseries, Science & Nature TV","As California's 2016 fire season rages, brave ..."
20,80060297,Movie,Manhattan Romance,Tom O'Brien,"Tom O'Brien, Katherine Waterston, Caitlin Fitz...",United States,"September 8, 2017",2014,TV-14,98 min,"Comedies, Independent Movies, Romantic Movies",A filmmaker working on a documentary about lov...

In [ ]:
idk = df['country'].str.split(',').explode().replace('',np.nan).dropna().str.strip().sort_values().unique()
idk

<ArrowStringArray>
[         'Afghanistan',              'Albania',            'Argentina',
              'Armenia',            'Australia',              'Austria',
           'Azerbaijan',           'Bangladesh',              'Belgium',
              'Bermuda',
 ...
              'Ukraine', 'United Arab Emirates',       'United Kingdom',
        'United States',              'Uruguay',         'Vatican City',
            'Venezuela',              'Vietnam',         'West Germany',
             'Zimbabwe']
Length: 110, dtype: str

In [ ]:
content_type = df['type'].dropna().unique()
fil_df = df[df['type'].isin(content_type)]
fil_df.head()
#fil_df = fil_df[fil_df['country']] #.apply(lambda x: any(c.strip() in idk for c in x.split(',')))] 
fil_df[fil_df['country'].apply(lambda x: any(c.strip() in idk for c in x.split(',')) if isinstance(x, str) else False)]
#yayyy

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...,...
6227,80005756,TV Show,The Adventures of Figaro Pho,NaN,"Luke Jurevicius, Craig Behenna, Charlotte Haml...",Australia,NaN,2015,TV-Y7,2 Seasons,"Kids' TV, TV Comedies","Imagine your worst fears, then multiply them: ..."
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [ ]:
df[df['country'].isin([''," "])]
#so there is no item in country with a blank item....oK good

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [ ]:
df1 = pd.DataFrame(data={'name':['Mossa','Tossa','Lossa','Khossa'],"salary":[600,300,300,500]})
# df1[df['salary'].apply(lambda x:x if x.count)]
# df1[df1['salary'] > 200 and df['salary']]
fil1 = df1['salary'].drop_duplicates(keep=False).sort_values(ascending=False)
# n = 2
# idk1 = fil1.iloc[n-1]
# pd.DataFrame({f'getNthHighestSalary({n})':[idk1]})
df1[df1['salary'].isin(fil1)]

     name  salary
0   Mossa     600
3  Khossa     500

In [ ]:
users = pd.DataFrame(data={'name':['Mossa','Tossa','Lossa','Khossa'],"email":['jonathanisgreat','bella-@leetcode.com','sally.come@leetcode.com','quarz#2020@leetcode.com' ]})
valid_emails = users['email'].str.contains(r'^[a-zA-Z][a-zA-Z0-9_.-]*@leetcode\.com$', regex=True)
users.loc[valid_emails]

    name                    email
1  Tossa      bella-@leetcode.com
2  Lossa  sally.come@leetcode.com

In [ ]:
lst = [0.01,0,0]
count=1
rank=[]
if len(lst) == 1:
    rank.append(count)
elif len(lst) == 2 and lst[0] == lst[1]:
    rank.extend([count,count])
else:
    for i in range(0,len(lst)-1):
        if i == len(lst) - 2 and lst[-1] == lst[i+1]:
            if lst[len(lst) - 2] == lst[-1]:
                rank.extend([count,count])
            else:
                rank.extend([count,count+1])
        elif lst[i]==lst[i+1]:
                rank.extend([count])
        else:
            rank.append(count)
            count+=1
df2 = pd.DataFrame({'score':pd.Series(lst),'rank':pd.Series(rank)})
df2
#i hated you to death bye

   score  rank
0   0.01     1
1   0.00     2
2   0.00     2

In [ ]:
nums = [1,2,3,4,4,4,5,6]
nums1 = pd.Series(data=nums)
nums1.drop_duplicates(inplace=True)
list(nums1)

[1, 2, 3, 4, 5, 6]

In [ ]:
data=fil_df['release_year'].value_counts().sort_index()
data.index

Index([1925, 1942, 1943, 1944, 1945, 1946, 1947, 1954, 1955, 1956, 1958, 1959,
       1960, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972,
       1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984,
       1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996,
       1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
       2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020],
      dtype='int64', name='release_year')

In [ ]:
df3 = pd.DataFrame({'id':[1,2,3,4],'email':['a@abc.com','c@abc.com','a@abc.com','a@abc.com']})
df4=pd.DataFrame({'id':[],'email':[]})
umm=pd.Series(df3['email'].value_counts() > 1)
#df3['email'].drop_duplicates(keep=False)
#umm.apply(lambda x:x for c in umm if c == True)
umm
yA=df3[df3.duplicated(subset=['email'],keep='first')]
new_df = pd.DataFrame({'Email':yA['email'].unique()})
new_df

       Email
0  a@abc.com

In [ ]:
df5=pd.DataFrame({'id':[1,2,3,4],'name':['Joe','Henry','Sam','Max'],'salary':[70,80,60,90],'managerId':[3,4,None,None]})
df5.set_index('id',inplace=True)
df5

     name  salary  managerId
id
1     Joe      70        3.0
2   Henry      80        4.0
3     Sam      60        NaN
4     Max      90        NaN

In [ ]:
fil_df = df5[df5['managerId'].isin(df5.index)]
#fil_df['managerId'] = fil_df['managerId'].astype('Int64')
fil_df.set_index('managerId',inplace=True)
#fil_df.drop('id',axis=1)
fil_df

            name  salary
managerId
3.0          Joe      70
4.0        Henry      80

In [ ]:
ok = fil_df.join(df5,how='inner',lsuffix='_emp',rsuffix='_manager')
empnam = ok['name_emp'][ok['salary_emp']>ok['salary_manager']]
okay = pd.DataFrame({'Employee':empnam}).reset_index().drop(columns='managerId')
okay

  Employee
0      Joe

In [ ]:
nums = [0,0,1,1,1,2,2,2,3,3,4]
lenn = len(nums)

for i in range(-1,-lenn,-1):
    lenn = len(nums)
    if nums[i] in nums[:i]:
        del nums[i]
nums

IndexError: list index out of range

In [ ]:
lst = list(range(-1,-11,-1))
lst[:-1]

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [ ]:
x = -123
x = str(x)
signed = -1 if '-' in x else 1
x = x.strip('-')
y = x[::-1]
y = int(y) * signed
if pow(-2,31) <= y <= pow(2,31):
    print(y)
else:
    print(0)

-321

In [ ]:
nums=[1,0.0100,2]
for i in range(0,len(nums)):
    x = list(str(nums[i]).strip('0'))
    if '.' in x:
        x.remove('.')
    # y = list(x)
    val = 0
    for j in x:
        val+=int(j)
    if i == val:
        print(i)

1
2

In [ ]:
import re
import string
s="abcde"
p='a?c.*'
if p == '*' or s=='':
    print(True)
# search = re.findall(p,s)
# if search:
#     print(True)
# else:
#     print(False)
# for i in string.punctuation:
#     if i in p:
#         print('yes!')
idk = False
if p[0] in string.ascii_lowercase:
    new_p='$'+p
    idk = True
else:
    new_p='.'+p
    idk = True
    #break

if idk:
    search_p = re.fullmatch(new_p,s)
    if search_p:
        print(True)
    else:
        print(False)
else:
    if p == s:
        print(True)
    else:
        print(False)

False

In [ ]:
s="abcde"
p='a+c.*'
yuh = re.fullmatch(p,s)
if yuh:
    print(True)

In [ ]:
p='c*a*b'
if p[0] in string.ascii_lowercase:
    new_p='^'+p
new_p

'^c*a*b'

In [ ]:
a=0b11
b=0b1
bin_sum = a+b
bin(bin_sum)[2:]

'100'

In [ ]:
new_a = '11'
new_b = '1'
bin_sum = int(new_a,2) + int(new_b,2)
bin(bin_sum)[2:]

'100'

In [ ]:
from datetime import timedelta
weather = pd.DataFrame({'id':[1,2,3,4],'recordDate':['2015-1-31','2015-2-1','2015-2-3','2015-2-4'],'temperature':[10,25,20,30]})
true_id = []
weather['recordDate'] = pd.to_datetime(weather['recordDate'])
weather = weather.sort_values(by='recordDate',ignore_index=True)

for i in range(1,len(weather['id'])):
    if weather['recordDate'][i] - weather['recordDate'][i-1] == timedelta(1):
        if weather['temperature'][i] > weather['temperature'][i-1]:
            true_id.append(weather['id'][i])

pd.DataFrame({'id':true_id})
# weather['recordDate'][1].day - weather['recordDate'][0].day == 1

   id
0   2
1   4

In [ ]:
s = "()(())((()()))"
j = 0
lst = []
for i in s:
    if i == '(':
        j+=1
        lst.append(j)
    elif i == ')':
        j-=1
        lst.append(j)
    else:
        continue

print(max(lst) if lst else 0)
print(lst)

3
[1, 0, 1, 2, 1, 0, 1, 2, 3, 2, 3, 2, 1, 0]

In [ ]:
from datetime import timedelta
date1 = pd.to_datetime('2019-12-31')
date2 = pd.to_datetime('2020-1-1')
diff = date2-date1
diff == timedelta(1)
#diff

True

In [ ]:
s = "([]"
lst = []
if s.startswith((')',']','}')):
    print('Yes')
if s.endswith(('(','[','{')):
    print('Yes!')
for i in s:
    if i == '(' or i == '[' or i == '{':
        lst.append(i)
    elif lst:
        if i == ')' and lst[-1] == '(':
            lst.pop(-1)
        elif i == ']' and lst[-1] == '[':
            lst.pop(-1)
        elif i == '}' and lst[-1] == '{':
            lst.pop(-1)
        else:
            print(False)
    else:
        print(False)

if lst:
    print(False)
else:
    print(True)

False

In [ ]:
s = 'sadbutsad'
n = 'no'
s.find(n)

-1

In [105]:
import numpy as np
df6 = pd.DataFrame({'EmpId':[1,2,3],'Name':['Fan','Lan','San'],'EmpNo':[23,56,77],'Supervisor':[2,None,3],'Salary':[3000,5000,4000]})
bonus_df = pd.DataFrame({'EmpId':[2],'bonus':[2000]})
new_dff = pd.merge(df6,bonus_df,how='outer')
# new_dff['Name'][new_dff['bonus']<1000]
#new_dff['bonus'] = new_dff['bonus'].fillna(0)
names = new_dff['Name'][new_dff['bonus'].isna() | (new_dff['bonus'] <1000)]
bonus = new_dff['bonus'][new_dff['bonus'].isna() | (new_dff['bonus'] <1000)]

# s1 = pd.DataFrame({'bonus':[0,2000,0]})
# s1['bonus'].replace(0,None)
new_dff['bonus'][new_dff['bonus']==np.nan]
new_dff.iloc[0]['bonus']
bonus

0   NaN
2   NaN
Name: bonus, dtype: float64

In [119]:
num_list = [
    38, 38, 14, 14, 14, 13, 13, 13, 8, 8, 8, 6, 6, 6, 23, 23, 23, 1, 1, 1, 
    38, 38, 38, 39, 39, 39, 49, 49, 49, 23, 23, 23, 10, 10, 10, 42, 42, 42, 21, 21, 
    21, 9, 9, 9, 32, 32, 32, 37, 37, 37, 42, 42, 42, 8, 8, 8, 17, 17, 17, 11, 
    11, 11, 2, 2, 2, 15, 15, 15, 7, 7, 7, 49, 49, 49, 23, 23, 23, 33, 33, 33, 
    32, 32, 32, 0, 0, 0, 17, 17, 17, 37, 37, 37, 18, 18, 18, 26, 26, 26, 26, 26, 
    26, 13, 13, 13, 0, 0, 0, 47, 47, 47, 37, 37, 37, 47, 47, 47, 15, 15, 15, 12, 
    12, 12, 44, 44, 44, 14, 14, 14, 46, 46, 46, 7, 7, 7, 14, 14, 14, 30, 30, 
    30, 13, 13, 13, 0, 0, 0, 47, 47, 47, 16, 16, 16, 38, 38, 38, 23, 23, 23, 
    33, 33, 33, 47, 47, 47, 32, 32, 32, 27, 27, 27, 25, 25, 25, 41, 41, 41, 36, 
    36, 36, 38, 38, 38, 4, 4, 4, 17, 17, 17, 27, 27, 27, 28, 28, 28, 48, 48, 
    48, 15, 15, 15, 24, 24, 24, 12, 12, 12, 35, 35, 35, 38, 38, 38, 18, 18, 18, 
    38, 38, 38, 25, 25, 25, 21, 21, 21, 25, 25, 25, 19, 19, 19, 36, 36, 36, 1, 
    1, 1, 11, 11, 11, 35, 35, 35, 35, 35, 35, 3, 3, 3, 16, 16, 16, 7, 7, 
    7, 1, 1, 1, 25, 25, 25, 14, 14, 14, 45, 45, 45, 43, 43, 43, 27, 27, 27, 
    4, 4, 4, 32, 32, 32, 23, 23, 23, 39, 39, 39, 33, 33, 33, 31, 31, 31, 15, 
    15, 15, 32, 32, 32, 15, 15, 15, 23, 23, 23, 0, 0, 0, 26, 26, 26, 44, 44, 
    44, 43, 43, 43, 39, 39, 39, 23, 23, 23, 34, 34, 34, 3, 3, 3, 1, 1, 
    1, 32, 32, 32, 4, 4, 4, 18, 18, 18, 18, 18, 18, 21, 21, 21, 19, 19, 19, 
    25, 25, 25, 45, 45, 45, 9, 9, 9, 35, 35, 35, 7, 7, 7, 43, 43, 43, 46, 
    46, 46, 44, 44, 44, 2, 2, 2, 28, 28, 28, 35, 35, 35, 20, 20, 20, 42, 42, 
    42, 39, 39, 39, 5, 5, 5, 8, 8, 8, 41, 41, 41, 8, 8, 8, 19, 19, 19, 
    48, 48, 48, 45, 45, 45, 44, 44, 44, 23, 23, 23, 1, 1, 1, 43, 43, 43, 44, 
    44, 44, 19, 19, 19, 11, 11, 11, 42, 42, 42, 37, 37, 37, 31, 31, 31, 20, 
    20, 20, 14, 14, 14, 50, 50, 50, 44, 44, 44, 36, 36, 36, 24, 24, 24, 34, 
    34, 34, 25, 25, 25, 16, 16, 16, 17, 17, 17, 27, 27, 27, 13, 13, 13, 18, 
    18, 18, 25, 25, 25, 31, 31, 31, 30, 30, 30, 5, 5, 5, 47, 47, 47, 6, 6, 
    6, 47, 47, 47, 28, 28, 28, 27, 27, 27, 4, 4, 4, 42, 42, 42, 35, 35, 35, 
    47, 47, 47, 38, 38, 38, 22, 22, 22, 38, 38, 38, 30, 30, 30, 31, 31, 31, 2, 
    2, 2, 26, 26, 26, 44, 44, 44, 13, 13, 13, 6, 6, 6, 37, 37, 37, 4, 4, 
    4, 41, 41, 41, 8, 8, 8, 48, 48, 48, 6, 6, 6, 21, 21, 21, 27, 27, 27, 
    24, 24, 24, 29, 29, 29, 14, 14, 14, 5, 5, 5, 5, 5, 5, 33, 33, 33, 
    37, 37, 37, 45, 45, 45, 19, 19, 19, 9, 9, 9, 17, 17, 17, 36, 36, 36, 
    26, 26, 26, 38, 38, 38, 39, 39, 39, 41, 41, 41, 16, 16, 16, 1, 1, 1, 
    23, 23, 23, 25, 25, 25, 40, 40, 40, 24, 24, 24, 25, 25, 25, 41, 41, 41, 
    16, 16, 16, 48, 48, 48, 7, 7, 7, 44, 44, 44, 15, 15, 15, 43, 43, 43, 
    29, 29, 29, 27, 27, 27, 27, 27, 27, 33, 33, 33, 25, 25, 25, 17, 17, 17, 
    2, 2, 2, 11, 11, 11, 29, 29, 29, 28, 28, 28, 22, 22, 22, 42, 42, 42, 
    47, 47, 47, 31, 31, 31, 38, 38, 38, 31, 31, 31, 39, 39, 39, 33, 33, 33, 
    43, 43, 43, 42, 42, 42, 31, 31, 31, 32, 32, 32, 20, 20, 20, 9, 9, 9, 
    49, 49, 49, 24, 24, 24, 47, 47, 47, 9, 9, 9, 3, 3, 3, 17, 17, 17, 
    35, 35, 35, 26, 26, 26, 30, 30, 30, 33, 33, 33, 42, 42, 42, 1, 1, 1, 
    26, 26, 26, 31, 31, 31, 17, 17, 17, 38, 38, 38, 43, 43, 43, 30, 30, 30, 
    0, 0, 0, 22, 22, 22, 43, 43, 43, 4, 4, 4, 4, 4, 4, 42, 42, 42, 
    19, 19, 19, 45, 45, 45, 4, 4, 4, 15, 15, 15, 12, 12, 12, 20, 20, 20, 
    29, 29, 29, 10, 10, 10, 4, 4, 4, 47, 47, 47, 3, 3, 3, 10, 10, 10, 
    45, 45, 45, 40, 40, 40, 5, 5, 5, 20, 20, 20, 30, 30, 30, 3, 3, 3, 
    50, 50, 50, 32, 32, 32, 39, 39, 39, 12, 12, 12, 36, 36, 36, 30, 30, 30, 
    15, 15, 15, 33, 33, 33, 36, 36, 36, 2, 2, 2, 13, 13, 13, 42, 42, 42, 
    35, 35
]

In [136]:
df7 = pd.DataFrame({'num':num_list})
curr = None
count = 0
consec_n = []
for n in df7['num']:
    if curr != n:
        curr = n
        count = 0
    count+=1
    if count == 3:
        consec_n.append(n)

df8 = pd.DataFrame({'ConsecutiveNums':list(set(consec_n))})
s2 = pd.Series(consec_n)
len(s2.unique())
len(df8)

51

In [ ]:
nums = [3,2,1,4]
#len([[],1, 12 , 13 , 14, 15, 2 , 23 , 24 , 25 , 3, 34 , 35 , 4 , 45, 5])

# nums = 1, len = 2
# nums = 2, len = 4
# nums = 3, len = 8
# nums = 4, len = 16

#any pattern? idk

power_num = [[],nums]
if len(nums) == 1:
    print([[]]+[nums])

else:
    for i in nums:
        power_num.append([i])
        for j in nums[nums.index(i)+1:]:
            val = [i,j]
            if val not in power_num:
                power_num.append(val)

len(power_num)

numm = [[1],[1,3]]
[3,1] in numm

False

In [31]:
[3,2,4,1]

len([[], [3], [3,2] , [3,4], [3,1], [3,2,4], [3,2,4,1] ,[3,2,1],[3,4,1], [2], [2,4], [2,1], [2,4,1], [4], [4,1], [1]])

16

In [51]:
colors = [2,0,2,1,1,0]

zeros = colors.count(0)
ones = colors.count(1)
twos = colors.count(2)

colors.clear()
colors.extend([0 for i in range(zeros)])
colors.extend([1 for i in range(ones)])
colors.extend([2 for i in range(twos)])

colors

[0, 0, 1, 1, 2, 2]

In [8]:
import pandas as pd
import numpy as np

In [87]:
employees = pd.DataFrame({'employee_id':[2,4,5,6,7,8,9], 'Name':['P1','P2','P3','P4','P5','P6','P7']})
salaries = pd.DataFrame({'employee_id':[5,1,4,10,11], 'Salary':[80,90,100,10,20]})

new_df = pd.merge(employees, salaries, on='employee_id', how='outer')
#new_df = new_df.replace(np.nan,-1)

# new_df['Name'] == -1
# new_df['Salary'] == -1

emps1 = new_df['employee_id'][new_df['Name'].isna()].to_list()
emps2 = new_df['employee_id'][new_df['Salary'].isna()].to_list()

missing_emps = emps1 + emps2

missing_df = pd.DataFrame({'employee_id':missing_emps})
missing_df.sort_values(by='employee_id')

   employee_id
0            1
3            2
4            6
5            7
6            8
7            9
1           10
2           11

In [110]:
emails = pd.DataFrame({'id':[3,2,1], 'email':['a@a.com','b@b.com','a@a.com']})
emails = emails.sort_values(by='id')
emails['email'] = emails['email'].drop_duplicates(keep='first')
emails.dropna(inplace=True)
emails

   id    email
2   1  a@a.com
1   2  b@b.com